### PR TITLE
issue88 add amount field in UI

### PR DESCRIPTION
**Pull request by ccMolly**
add amount field in UI

### CODE REVIEW

**Review by yuhanzz — COMMENTED** [review]
Hi Mingxi, do we have any field for providing the shopcart_id information? Or do we have any default value for shopcart_id? Right now it seems like pressing the purchase button would send a purchase request with None as the shopcart_id.

**Comment by hlillian246** [comment]
Mingxi, I might need to change a few things for the purchase endpoint from the backend so I will do a PR and then you can make the changes accordingly. Sorry for the inconvenience.

**Review by xz2643 — APPROVED** [review]

**Comment by hlillian246** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/8622bb4b-e9ad-4e39-a00c-0c751a272894?env_id=ibm:yp:us-south "devops-product-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/5c1eb742-fd46-4555-8895-7c11a8c96e76 "nyu-devops-products-pipeline") deployed [products](https://github.com/Devops-2020-Products/products/releases/tag/deploy-ibm-yp-us-south-yangxinshirley123-gmail.com-dev-20201118-062420 "deploy-ibm-yp-us-south-yangxinshirley123-gmail.com-dev-20201118-062420") to [dev](https://console.bluemix.net/apps/b0967d75-5ac0-4782-ad34-502e672078fe?env_id=ibm:yp:us-south "ibm:yp:us-south:yangxinshirley123@gmail.com:dev"), including commit 1729ea61e024ede18456e8a5d7dfec4fce37161c

**Comment by hlillian246** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/8622bb4b-e9ad-4e39-a00c-0c751a272894?env_id=ibm:yp:us-south "devops-product-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/5c1eb742-fd46-4555-8895-7c11a8c96e76 "nyu-devops-products-pipeline") deployed [products](https://github.com/Devops-2020-Products/products/releases/tag/deploy-ibm-yp-us-south-yangxinshirley123-gmail.com-prod-20201206-004751 "deploy-ibm-yp-us-south-yangxinshirley123-gmail.com-prod-20201206-004751") to [prod](https://console.bluemix.net/apps/642d538c-5e7d-4ba0-a9db-6302cc619b14?env_id=ibm:yp:us-south "ibm:yp:us-south:yangxinshirley123@gmail.com:prod"), including commit 1729ea61e024ede18456e8a5d7dfec4fce37161c

**Pull request merged**
